from typing import Dict, List, Union

from pynamodb.expressions.operands import Path


def get_path_segments(document_path: Union[str, Path]) -> Union[List[str], List[Path]]: ...
def substitute_names(document_path: Union[str, Path], placeholders: Dict[str, str]) -> str: ...
def get_value_placeholder(value: Path, expression_attribute_values: Dict[str, str]) -> str: ...
